"""Offline manual source, maintained alongside the product workflow."""
CHAPTERS = {
"zh_CN": [
("start", "1. 首次启动与界面", "从 KabuForge 启动入口打开工作台。右上角选择简体中文、日本語或 English；语言会保存在当前工作区，切换不清除表单。左侧导航进入首页、我的策略、数据中心、回测结果、纸上交易、券商连接与运行记录。窄窗口下策略目录移到编辑区上方。", "有三条本地路径：合成演示、下载数据的价格研究、以及已准备好的本地真实研究包。普通向导表单不编辑已加载的 run；高级区用于打开、预检和审查声明式配置。", "next:demo"),
("demo", "2. 无需密钥的离线演示", "在首页点击“体验离线演示”。程序在当前工作区创建独立的虚构数据、策略和模拟账户，不读取旧生产账本。等待任务完成后，进入“我的策略”，选择“质量与趋势（合成演示）”，输入名称、持仓数量、调仓频率、质量占比、初始资金和费用。", "点击“检查并创建策略”后检查摘要，再点击“开始回测”。程序先预检，再启动历史模拟；失败会停止，不会绕过校验。曲线只来自完成的计算。演示日期固定在 2024 年 5 月；持仓上限取决于虚构股票池。虚构收益不能作为策略有效性的证据。", "next:strategy"),
("connect", "3. 配置 J-Quants API key", "进入数据中心，在 J-Quants 连接区输入你自己的 API key。使用显示/隐藏按钮检查输入，点击测试连接。连接测试是只读数据请求，不会下单。无效密钥、权限不足、限流和网络错误会显示可处理的提示。不要把密钥粘贴到策略描述、截图或日志。", "默认仅在当前会话使用密钥。只有勾选安全保存后才存入 Windows 凭据管理器；这不是普通配置文件。可删除保存的凭据。连接成功不保证全部历史数据都在你的订阅权限内，最终以下载响应为准。测试与下载可能使用订阅的 API 请求额度。", "next:download"),
("download", "4. 下载、更新与中断恢复", "在数据中心填写股票代码列表、开始日期和结束日期，再开始下载。建议先用少量股票和短日期区间验证。数据仅写入当前工作区的 jquants_downloads 目录。下载页显示进度，可取消；重试相同请求会使用已经校验的分页检查点，不把部分文件当完整数据。", "扩展日期范围会形成另一份请求记录，不会改写原有研究证据。完成后清单会接入“我的策略”的价格动量模板。重新打开软件时可通过文件选择器选择之前的 manifest.json。数据来自当前取得的历史版本，不自动代表严格的历史可见版本；下载时间不是历史 available_at。", "next:market"),
("strategy", "5. 用表单创建策略", "给策略取一个易识别的名称。模板决定数据和计算方式：质量与趋势使用合成演示；价格动量使用已下载的日线数据。持仓数量为目标上限，等权指选中股票的目标权重相同。调仓支持每日、每周、每月。费用以单边百分比输入，例如 0.10 表示 0.10%，并非 10%。", "质量占比仅用于合成演示，剩余为趋势因子；两者不是价格动量模板的参数。价格动量使用观察期前的收盘价计算排名。初始资金以日元计。先创建并审阅策略，再开始回测；已通过 Ctrl+O 或 --run 加载本地研究包时，不要点“检查并创建策略”覆盖它。", "next:language"),
("language", "6. 自然语言辅助填写", "当前支持本地、受约束的三语表达，例如“每月选5只股票，等权”、“毎月5銘柄を均等配分”或“Select 5 stocks monthly, equal weight”。点击解析到表单，只会填写数量、频率和等权方式。", "含做空、杠杆、止损等未支持条件，或相互矛盾的数量/频率时，解析会提示不能完整理解，不应用猜测。解析结果仍需检查；其他参数用表单设置。此功能不访问外部 AI，不发送你的策略描述，也不自动创建或运行策略。", "next:results"),
("market", "7. 下载数据的价格研究", "完成下载后，选择价格动量模板，设置观察期、持仓数、调仓频率、初始资金和费用。数据必须包含有效价格，且每个参与股票覆盖同一研究日历；缺失开盘/收盘、停牌或样本不足时会拒绝研究，而非编造价格。", "该研究用前一交易日及更早的收盘信息排序，在下一交易日开盘价模拟调整，以收盘价估值。观察期需要预热，前若干天不产生交易。按完整股票池共同日期工作；当前采用连续份额、等权、现金账户的简化研究，不模拟整手、滑点、盘口或市场冲击，也不构成严格 PIT 认证。遇到拆股调整因子变化时拒绝运行，避免混用单位。", "next:realpack"),
("realpack", "8. 运行本地真实研究包", "本地准备流程生成的最小研究包包含 backtest.json、snapshot.json、timeline.json、account.json 及同目录的 Parquet 数据。以 --run 指向 backtest.json 启动，或按 Ctrl+O 选择它。导入后不要使用普通向导的“检查并创建策略”；该表单不是已加载 run 的编辑器。", "按 Ctrl+Shift+D 展开数据中心的高级诊断；同目录的 timeline.json 会自动加载。按 Ctrl+Return 预检，再按 Alt+4 到回测结果页，Ctrl+Shift+Return 运行模拟。整月验收覆盖 2025-04-01 至 2025-04-30 的同一 20 只股票：21 次决策、21 个 NAV 点、11 笔模拟成交，期末 NAV 为 0.9873801989。执行和估值从 4 月 2 日延续至 5 月 1 日，后者完成 4 月 30 日决策后的下一交易日执行与估值。前收盘只作计划参考价，执行开盘报价另行结算。结果为 RESEARCH-ONLY：未证明历史 API 可见时间、历史版本或全策略等价。", "next:results"),
("results", "9. 阅读和比较回测结果", "回测结果页显示净值、回撤、交易记录和摘要。净值从初始资金归一化；回撤表示相对于此前净值峰值的跌幅。未提供基准时不会生成虚构基准。价格研究的模型说明与合成执行模型不同，应连同结果一起阅读。", "表格支持筛选、排序、复制和 CSV 导出。运行比较检查输入和配置身份，不能仅凭两条曲线就认定差异来自某个参数。所有结果应保留输入快照和费用设置。失败或取消的任务不能作为完成结果使用。", "next:paper"),
("paper", "10. 纸上交易与账户边界", "合成演示创建后，可在顶部执行模式选择独立 Paper 模拟账户。模式切换不会自动交易。重新预检后先生成计划，审阅目标和费用，再执行独立模拟。运行结果中的账本路径会填入查询框，可只读查看账户、订单、事件和成交。", "当前价格研究结果不能直接充当已认证的 Paper 输入。高级 Paper 流程需要显式快照、时间与执行报价。UNKNOWN 或需要对账的状态会阻止新执行，应查询和审查，不要盲目重发。完整自动恢复仍未启用；真实券商账户也未启用。", "next:records"),
("records", "11. 保存、运行记录和截图", "向导创建的策略保存在当前工作区，使用独立目录，重复名称不覆盖旧策略。高级编辑可保存副本，原配置保留。运行记录保存请求、进程身份、输出目录、日志、退出状态和配置快照。应用只取消自己启动的任务，不处理其他程序。", "可选用 --record-dir 指定一个新的记录目录启动。Ctrl+Shift+R 开始或停止本窗口录制，Ctrl+Shift+P 保存单帧；PNG 仅含真实 Qt 客户区，不含桌面、鼠标或文件对话框。GIF 是步骤摘要，不是连续视频。按 Alt+7 查看运行记录，截图前隐藏密钥和个人路径。", "next:trouble"),
("trouble", "12. 常见问题", "连接失败：检查 key 是否有效、网络能否访问 J-Quants、套餐是否包含请求数据；限流时等待再试。下载中断：保持相同代码和日期重试，不能把未完成清单用于回测。回测按钮不可用：先完成策略创建，处理预检错误，并等待正在运行的任务。", "界面过窄：放大窗口，折叠高级设置；表格允许自身横向滚动。旧 JSON 不兼容：查看高级诊断并显式转换，程序不自动删除未知字段。结果无交易：检查预热期、样本数量、风险限制和调仓日期。错误仍未解决时保存运行记录，报告操作步骤，不提供密钥。", "next:help"),
("help", "13. 手册搜索与快捷键", "点击侧栏“操作手册”或按 F1 打开内置离线手册。左侧目录点击即可跳到章节；搜索框同时检索标题和正文，结果可直接跳到对应章节。右侧上一处/下一处在当前手册中查找关键词。章节末尾的链接可跳到下一章；语言切换后保留当前章节。", "Alt+1 到 Alt+7 切换工作页；Ctrl+O 导入本地 run JSON；Ctrl+Shift+O 打开已保存的回测报告；Ctrl+Shift+L 循环界面语言；Ctrl+Return 预检；Ctrl+Shift+D 展开数据高级诊断；Ctrl+Shift+Return 运行回测模拟；Ctrl+S 保存配置副本。手册 HTML 位于相对路径 framework_v2/docs，可离线阅读。", "next:start"),
],
"ja_JP": [
("start", "1. 起動と画面", "KabuForge のランチャーから起動します。右上で日本語・简体中文・Englishを選択できます。言語はワークスペースに保存され、切り替えても入力は失われません。左のナビゲーションからホーム、マイ戦略、データセンター、結果、ペーパートレード、証券会社接続、実行履歴へ移動します。狭い画面では戦略一覧を上に配置します。", "ローカルの経路は、合成デモ、取得データの価格リサーチ、準備済みの実データ研究パッケージの三つです。通常フォームは読み込んだ run を編集しません。詳細設定は宣言的設定の読込、事前確認、審査に使います。", "next:demo"),
("demo", "2. キー不要のオフラインデモ", "ホームのオフラインデモをクリックします。架空のデータ・戦略・模擬口座を現在のワークスペースに作成し、既存の運用台帳には触れません。完了後、マイ戦略でクオリティとトレンドの合成デモを選び、名前、銘柄数、頻度、比率、資金、手数料を入力します。", "戦略を確認して作成し、バックテスト開始を押します。検証後にシミュレーションが始まり、失敗時には停止します。曲線は計算結果のみを表示します。デモ期間は2024年5月で、銘柄数は架空のユニバースに制限されます。架空の収益は戦略の有効性を証明しません。", "next:strategy"),
("connect", "3. J-Quants APIキー", "データセンターで自分のAPIキーを入力します。表示・非表示を切り替えて確認し、接続テストを実行します。テストは読取専用のデータ取得で、発注は行いません。無効なキー、権限、レート制限、ネットワークの問題が表示されます。キーを戦略説明やログ、スクリーンショットに含めないでください。", "既定ではセッション中のみ保持します。安全な保存を選んだ場合だけWindows資格情報マネージャーに保存します。通常の設定JSONには書きません。保存したキーは削除できます。接続成功は全期間の取得権限を保証せず、実際のレスポンスに従います。テストと取得はAPI利用枠を消費する場合があります。", "next:download"),
("download", "4. ダウンロードと再開", "銘柄コード、開始日、終了日を指定して取得します。最初は少数銘柄・短期間を推奨します。保存先は現在のワークスペース内のjquants_downloadsです。進捗表示と中止ボタンがあります。同じ条件の再試行は検証済みページから再開し、未完了ファイルを完全なデータとして扱いません。", "期間を広げると別のリクエスト記録になります。完了した清単は価格モメンタムの入力に使用できます。再起動後は以前のmanifest.jsonを選択できます。取得した履歴は現在の版であり、過去時点での可視性を保証しません。取得時刻を過去のavailable_atとして使いません。", "next:market"),
("strategy", "5. フォームで戦略を作成", "識別しやすい名前を付けます。クオリティとトレンドは合成データ、価格モメンタムは取得した日足を使います。保有銘柄数は目標の上限です。均等配分では選択銘柄の目標比率を等しくします。頻度は毎日・毎週・毎月です。片道手数料は百分率で、0.10は0.10%を意味します。", "クオリティ比率は合成デモ専用で、残りがトレンドです。価格モメンタムでは観察期間前の終値を用いて順位を計算します。初期資金は円単位です。作成した設定を確認してから実行してください。Ctrl+O または --run で実データ研究パッケージを読み込んだ場合は、「戦略を作成」を押して上書きしないでください。", "next:language"),
("language", "6. 文章入力の補助", "ローカル解析は限られた三言語表現に対応します。例は「毎月5銘柄を均等配分」、「每月选5只股票，等权」、「Select 5 stocks monthly, equal weight」です。フォーム反映で変更されるのは銘柄数、頻度、均等配分です。", "空売り、レバレッジ、損切りなど未対応の条件や矛盾する数・頻度は推測せず拒否します。結果を確認し、その他の項目はフォームで設定します。外部AIは使わず文章を送信しません。解析のみでは戦略の作成・実行は始まりません。", "next:results"),
("market", "7. 実データの価格リサーチ", "取得完了後、価格モメンタムを選び、観察期間、銘柄数、頻度、資金、手数料を設定します。有効価格と全銘柄の共通カレンダーが必要です。始値・終値の欠損、売買停止、データ不足を補間で隠さず拒否します。", "前営業日以前の終値で順位を決め、翌営業日の始値で調整を模擬し、終値で評価します。最初の観察期間は準備期間です。連続数量・均等配分・現金口座の簡易研究であり、単元株、スリッページ、板、市場影響は再現しません。厳密なPIT認証ではありません。株式分割の調整係数が変化する期間は単位混在を避けるため拒否します。", "next:realpack"),
("realpack", "8. ローカル実データ研究パッケージ", "ローカル準備処理が作る最小パッケージには backtest.json、snapshot.json、timeline.json、account.json と同じフォルダーの Parquet データがあります。--run で backtest.json を指定して起動するか、Ctrl+O で選択します。読込後は通常フォームの「戦略を作成」を使わず、run を上書きしません。", "Ctrl+Shift+D でデータセンターの詳細診断を開くと、同じフォルダーの timeline.json が自動で読み込まれます。Ctrl+Return で事前確認、Alt+4 で結果ページへ移動し、Ctrl+Shift+Return でバックテストを実行します。月次受入れは同じ20銘柄で 2025-04-01 から 2025-04-30 を対象とし、判断21回、NAV点21個、模擬約定11件、期末NAVは 0.9873801989 でした。実行と評価は4月2日から5月1日までで、5月1日は4月30日の判断後の次取引日における実行と評価を完了するためです。前終値は計画用の参照、始値は別の約定価格です。RESEARCH-ONLY であり、過去 API 可視性、履歴版、全戦略等価性は証明しません。", "next:results"),
("results", "9. 結果の読み方と比較", "結果ページには純資産、ドローダウン、取引と要約を表示します。純資産は初期資金で正規化し、ドローダウンは過去のピークからの下落率です。ベンチマーク未指定時に架空の線を生成しません。価格研究と合成約定のモデルは異なるため、説明も確認してください。", "表はフィルター、ソート、コピー、CSV出力に対応します。比較では入力と設定の識別情報を確認します。曲線だけで特定パラメータの効果を断定しないでください。入力スナップショットと費用を保存し、失敗・中止の処理を完了結果として扱わないでください。", "next:paper"),
("paper", "10. ペーパートレード", "合成デモ作成後、上部の実行モードで独立Paper口座を選べます。モード変更だけでは取引しません。再検証後に計画を生成し、目標と費用を確認してから独立シミュレーションを実行します。台帳パスが入力され、口座・注文・イベント・約定を読取専用で確認できます。", "価格リサーチ結果を認証済みPaper入力として直接使用できません。詳細フローには明示的なスナップショット、時刻、価格が必要です。UNKNOWNや照合要求があれば新規実行を停止します。照会・確認を行い、再送しないでください。完全自動復旧と実口座は無効です。", "next:records"),
("records", "11. 保存と記録", "ウィザードの戦略はワークスペースの独立フォルダーに保存され、同名でも上書きしません。詳細編集はコピー保存です。実行履歴には要求、PID、出力先、ログ、終了状態、設定スナップショットがあります。中止対象はこのアプリが開始した処理だけです。", "任意で --record-dir に新しい記録フォルダーを指定して起動できます。Ctrl+Shift+R でこのウィンドウの録画を開始・停止し、Ctrl+Shift+P で単フレームを保存します。PNG は実際の Qt クライアント領域だけで、デスクトップ、マウス、ファイル選択画面を含みません。GIF は連続動画ではなく手順の要約です。Alt+7 で実行履歴を開き、撮影前にキーと個人パスを隠してください。", "next:trouble"),
("trouble", "12. トラブルシューティング", "接続エラー：キー、ネットワーク、契約範囲を確認します。レート制限時は待って再試行します。中断：同じ条件で再開し、未完了清単を研究に使いません。実行ボタンが無効：戦略作成、検証エラーの解決、他処理の完了を確認してください。", "画面が狭い：ウィンドウを広げ詳細設定を閉じます。表自体は横スクロール可能です。旧JSON：詳細診断を読み、明示的に変換します。不明項目は自動削除しません。取引がない：準備期間、銘柄数、リスク条件、日程を確認します。解決しなければ操作手順と記録を報告し、キーは添付しないでください。", "next:help"),
("help", "13. マニュアル検索とショートカット", "側栏の操作マニュアルまたはF1でオフライン手冊を開きます。目次を押すと章に移動します。検索はタイトルと本文を対象とし、結果から章へジャンプできます。前・次ボタンは本文中の一致箇所を検索します。章末リンクは次章へ移動し、言語を変えても現在の章を維持します。", "Alt+1〜7でページ切替、Ctrl+Oでローカル run JSON を読込、Ctrl+Shift+Oで保存済みバックテスト報告を開き、Ctrl+Shift+Lで画面言語を循環、Ctrl+Returnで事前確認、Ctrl+Shift+Dでデータ詳細診断を開き、Ctrl+Shift+Returnでバックテストを実行します。HTML は相対パス framework_v2/docs にあり、オフラインで読めます。", "next:start"),
],
"en_US": [
("start", "1. Starting and navigating", "Launch KabuForge and choose English, 简体中文 or 日本語 at the top right. The workspace remembers the language; switching does not clear your input. Use the sidebar for Home, My strategies, Data center, results, paper trading, broker capabilities and run history. Narrow windows place the strategy list above the editor.", "There are three local paths: synthetic demo, price research from downloaded bars, and a prepared local real-data research package. The regular wizard form does not edit a loaded run; advanced controls open, preflight and inspect declarative configuration.", "next:demo"),
("demo", "2. Offline demo without a key", "Click Try offline demo on Home. It creates fictional data, a strategy and an isolated simulated account in this workspace, without reading production ledgers. When complete, open My strategies, choose Quality and trend (synthetic demo), and enter a name, holding count, frequency, quality allocation, capital and fees.", "Review and create the strategy, then start the backtest. Validation runs first and stops the workflow on failure. Charts only show computed results. The demo covers May 2024 and its fictional universe limits the holding count. Fictional returns are not evidence of investment performance.", "next:strategy"),
("connect", "3. Connecting J-Quants", "Enter your own API key in Data center. Toggle visibility to check it, then test the connection. The test is a read-only data request and does not place orders. Invalid keys, access restrictions, rate limits and network failures are reported. Never paste a key into strategy descriptions, screenshots or logs.", "Keys stay in memory by default. Only the explicit secure-save option writes to Windows Credential Manager, never ordinary strategy JSON. Saved keys can be deleted. A successful connection does not guarantee access to every historical period; the actual API response determines availability. Tests and downloads may consume your subscription request allowance.", "next:download"),
("download", "4. Downloading and resuming", "Enter stock codes and start/end dates, then download. Begin with a small universe and short interval. Files are confined to jquants_downloads inside this workspace. Progress and cancellation are available. Retrying the same request resumes verified page checkpoints; partial files are never treated as complete data.", "Extending the interval creates a separate request record rather than rewriting previous research evidence. A completed manifest can be used by the price momentum template. After restarting, select the previous manifest.json through the file picker. Downloaded history reflects the version available now, not certified historical visibility. Retrieval time is not historical available_at.", "next:market"),
("strategy", "5. Creating a strategy with controls", "Give the strategy a recognizable name. Quality and trend uses the synthetic demo; price momentum uses downloaded daily bars. Holding count is a target upper limit. Equal weight gives selected stocks equal target allocations. Rebalance daily, weekly or monthly. Fees are one-way percentages: 0.10 means 0.10%, not 10%.", "Quality allocation applies only to the synthetic demo; the remaining allocation is trend. Price momentum ranks using earlier closes over the selected lookback. Capital is in JPY. Create and inspect the configuration before running. When a local research package has been loaded with Ctrl+O or --run, do not click Review and create strategy: that wizard is not the loaded run editor.", "next:language"),
("language", "6. Sentence-assisted configuration", "The local parser supports constrained expressions in three languages, such as 'Select 5 stocks monthly, equal weight', '每月选5只股票，等权' and '毎月5銘柄を均等配分'. Parse into form only updates count, frequency and equal weighting.", "Unsupported requirements such as shorting, leverage or stop losses, and conflicting numbers or frequencies, are rejected rather than guessed. Inspect the result and set other parameters in the controls. No external AI is contacted and your sentence is not transmitted. Parsing alone never creates or runs a strategy.", "next:results"),
("market", "7. Price research with downloaded bars", "After download, select price momentum and set lookback, count, frequency, capital and fees. Valid prices and a common calendar across all selected stocks are required. Missing opens/closes, suspensions and insufficient history cause a refusal instead of invented prices.", "Ranking uses the previous session's close and earlier observations; rebalancing is simulated at the next session's open and valued at the close. Initial sessions are warm-up. This simplified cash-account research uses continuous units and equal weights, without board lots, slippage, order books or market impact. It is not strict PIT certification. Periods with changing split-adjustment factors are rejected to avoid mixing share units.", "next:realpack"),
("realpack", "8. Running a local real-data research package", "A minimum package prepared locally contains backtest.json, snapshot.json, timeline.json, account.json and Parquet data beside them. Start with --run pointing to backtest.json, or press Ctrl+O and select it. After loading, do not use the regular wizard's Review and create strategy action; it is not an editor for the loaded run.", "Press Ctrl+Shift+D to expand Data center advanced diagnostics; timeline.json beside the run loads automatically. Press Ctrl+Return to preflight, Alt+4 for Results, then Ctrl+Shift+Return to run the simulation. Month acceptance covers 2025-04-01 through 2025-04-30 with the same 20 stocks: 21 decisions, 21 NAV points, 11 simulated fills and ending NAV 0.9873801989. Execution and valuation run from April 2 through May 1; May 1 completes next-session execution and valuation after the April 30 decision. The prior close is a planning reference only; the opening execution quote settles separately. This is RESEARCH-ONLY: historical API visibility, historical versions and full-strategy equivalence are not proven.", "next:results"),
("results", "9. Reading and comparing results", "Results show NAV, drawdown, trades and a summary. NAV is normalized by initial capital; drawdown is the fall from the previous NAV peak. No benchmark is invented when absent. Read the model explanation: price research and synthetic quote matching use different assumptions.", "Tables support filtering, sorting, copying and CSV export. Comparisons inspect input and configuration identities; two curves alone do not establish a parameter's effect. Retain configuration snapshots and fee settings. Failed or cancelled tasks are not completed results.", "next:paper"),
("paper", "10. Paper trading boundaries", "After creating the synthetic demo, select the isolated Paper account in the top execution-mode selector. Switching modes does not execute trades. Check inputs again, create a plan, inspect targets and fees, then run the isolated simulation. The resulting ledger path is filled in for read-only account, order, event and fill queries.", "A price-research result is not certified Paper input. Advanced Paper workflows require explicit snapshots, timestamps and execution quotes. UNKNOWN or reconciliation-required states block new execution. Query and investigate instead of resending. Fully automatic recovery and live accounts remain disabled.", "next:records"),
("records", "11. Saving, recording and retaining evidence", "Wizard strategies are stored in independent workspace folders; repeated names do not overwrite earlier versions. Advanced editing saves a copy. Run history retains requests, process IDs, output paths, logs, exit states and configuration snapshots. Cancellation only affects processes started by this workbench.", "Optionally launch with --record-dir pointing to a new record directory. Ctrl+Shift+R starts or stops recording this window and Ctrl+Shift+P saves one frame. PNG contains only the actual Qt client area, never the desktop, mouse pointer or a file dialog. A GIF is a step summary, not continuous video. Alt+7 opens run history; hide keys and personal paths before capture.", "next:trouble"),
("trouble", "12. Troubleshooting", "Connection failed: check the key, network and subscription access; wait before retrying a rate limit. Interrupted download: retry identical codes and dates, and do not use an incomplete manifest. Disabled run button: create the strategy, resolve validation errors and wait for active jobs to finish.", "Cramped screen: enlarge the window and collapse advanced settings; tables can scroll horizontally. Incompatible old JSON: inspect diagnostics and convert explicitly; unknown fields are not silently removed. No trades: inspect warm-up, sample size, risk constraints and schedule. If unresolved, retain records and report the steps without including your key.", "next:help"),
("help", "13. Searching this guide and shortcuts", "Open User guide from the sidebar or press F1. Click the contents to jump to a chapter. Search checks both headings and full text; each result opens the corresponding chapter. Previous/next match searches occurrences in the document. Links at chapter ends lead to the next chapter. Language changes retain the current chapter.", "Alt+1 through Alt+7 change pages; Ctrl+O imports a local run JSON; Ctrl+Shift+O opens a saved backtest report; Ctrl+Shift+L cycles the interface language; Ctrl+Return preflights; Ctrl+Shift+D opens Data center advanced diagnostics; Ctrl+Shift+Return runs backtest simulation; Ctrl+S saves a config copy. HTML files are at the relative path framework_v2/docs and work offline.", "next:start"),
]}

# Implementation-specific details shared by GUI and exported HTML.
SUPPLEMENTS = {
 "zh_CN": {
  "start":"KabuForge 使用橙色锻台 Logo 和石墨背景，窗口与任务栏采用同源应用图标。橙色强调主要操作，不代表盈利或亏损；请以数值、正负号和文字状态为准。",
  "strategy":"重新启动后，可在我的策略页上方的下拉框选择已保存策略，再点击打开已保存策略。模板与资金参数会一起恢复。修改已加载的高级 JSON 后，须保存并重新检查，不能当作向导表单仍与旧参数一致。",
 "demo":"合成演示提供稀疏的三个观察日。周期调仓取所提供日历中每周或每月最后一个观察日，并非完整交易所日历；因此仅用于验证软件流程。",
  "realpack":"首次预检前，把高级诊断中的“决策时间（含时区）”设为 2025-04-01T23:59:00+09:00，“执行时间（含时区）”设为 2025-04-02T09:00:00+09:00。这两个表单值供预检和单次操作使用；历史回测逐期读取 timeline.json。价格和股票池按已有日期的收盘后研究口径使用，财务按披露时刻筛选，不另加 D-1。缺失收盘仅在估值时使用当时已知的最近有效收盘；原始因子输入不填补。",
  "market":"数量和目标资金按前日收盘价格确定，不读取次日开盘价来重新定量；实际开盘现金不足则整笔跳过该买单。每周/每月取预热完成后的第一个可用交易日。下载代码构成用户指定的研究股票池，不是历史全市场股票池，可能存在选择偏差。",
 },
 "ja_JP": {
  "start":"KabuForgeはオレンジの金床ロゴとグラファイトの背景を使用し、ウィンドウとタスクバーにも同じブランドのアイコンを使います。オレンジは主要操作の強調で、利益や損失を表しません。数値・符号・状態表示を確認してください。",
  "strategy":"再起動後はマイ戦略の上部リストから保存済み戦略を選び、開くボタンを押します。テンプレートと資金設定も復元します。詳細JSONを変更した場合は保存と再検証が必要で、元のフォームと一致していると見なしません。",
 "demo":"合成デモは3つの観察日だけを提供します。週次・月次は提供カレンダー内の最後の観察日を使い、完全な取引所カレンダーではありません。ソフトウェアの動作確認専用です。",
  "realpack":"最初の事前確認では、詳細診断の判断時刻を 2025-04-01T23:59:00+09:00、実行時刻を 2025-04-02T09:00:00+09:00 に設定します。この2項目は事前確認と単発操作に使用し、履歴バックテストの各期は timeline.json を読みます。価格と銘柄集合は既存日付の引け後という研究上の扱い、財務は開示時刻で選別し、追加の D-1 は設けません。終値が欠ける場合は評価だけにその時点で既知の直近有効終値を用い、元の因子入力は補完しません。",
  "market":"数量と資金配分は前日の終値で決め、翌日の始値で再計算しません。実際の始値で現金が不足すれば買注文全体をスキップします。週次・月次は準備期間後の最初の利用可能日です。指定コードは履歴全市場のユニバースではなく、選択バイアスがあり得ます。",
 },
 "en_US": {
  "start":"KabuForge uses the orange anvil logo and graphite surfaces, with the supplied application icon for the window and taskbar. Orange highlights primary actions; it does not indicate profit or loss. Read values, signs and status text.",
  "strategy":"After restarting, choose a saved strategy from the list above the form and click Open saved strategy. Template and capital settings are restored together. Editing advanced JSON requires saving and checking again; it invalidates any assumption that the original guided form still matches the configuration.",
 "demo":"The synthetic demo supplies only three observation sessions. Weekly/monthly schedules choose the last supplied observation in each period, not a complete exchange calendar. This is a software workflow check only.",
  "realpack":"Before the first preflight, set the advanced decision timestamp to 2025-04-01T23:59:00+09:00 and execution timestamp to 2025-04-02T09:00:00+09:00. These form values serve preflight and single-step operations; historical backtests read each period from timeline.json. Prices and universe data use their existing dates under an after-close research convention; financial data is filtered by disclosure time, with no additional D-1 lag. A missing close uses the most recent valid close known at that time for valuation only; raw factor inputs are not filled.",
  "market":"Quantities and target capital are sized from prior closes, never resized using the next open. A buy is skipped in full if the actual opening cost exceeds cash. Weekly/monthly research uses the first available session after warm-up. User-selected codes are not a historical whole-market universe and may introduce selection bias.",
 }}
for locale,extra in SUPPLEMENTS.items():
    CHAPTERS[locale]=[(key,title,*body[:-1],extra[key],body[-1]) if key in extra else (key,title,*body)
                      for key,title,*body in CHAPTERS[locale]]
