import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import zlib from 'node:zlib';
const root=path.resolve('dist');const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);const files=walk(root);const titles=new Set(),descs=new Set();let links=0;
for(const f of files.filter(f=>f.endsWith('.html'))){const html=fs.readFileSync(f,'utf8');const is404=f.endsWith('404.html');const route='/'+path.relative(root,f).replaceAll('\\','/').replace(/index.html$/,'');assert.match(html,/<h1[^>]*>.+?<\/h1>/s);const title=html.match(/<title>(.*?)<\/title>/s)[1];assert(!titles.has(title),'duplicate title');titles.add(title);const desc=html.match(/name="description" content="(.*?)"/)[1];assert(!descs.has(desc),'duplicate description');descs.add(desc);assert.equal((html.match(/rel="canonical"/g)||[]).length,1);assert.match(html,/<html lang="(?:en|ja)"/);assert.match(html,/id="main"/);if(!is404){assert(!html.includes('noindex'));assert(html.includes('href="https://kabuforge.com'+route+'"'));const alternates=[...html.matchAll(/rel="alternate" hreflang="(.*?)" href="(.*?)"/g)];assert.equal(alternates.length,3);for(const [,lang,url] of alternates){const r=new URL(url).pathname;const target=path.join(root,r,'index.html');assert(fs.existsSync(target),'missing alternate '+url);if(lang!=='x-default'){const opposite=fs.readFileSync(target,'utf8');assert(opposite.includes('href="https://kabuforge.com'+route+'"'),'nonreciprocal alternate');}}}else assert(html.includes('noindex'));
for(const [,src] of html.matchAll(/(?:href|src)="([^"#]+)"/g)){if(src.startsWith('/')){const clean=src.split('#')[0];assert(fs.existsSync(path.join(root,clean))||fs.existsSync(path.join(root,clean,'index.html')),'broken link '+src);links++;}}
for(const [,img] of html.matchAll(/(<img\b[^>]*>)/g)){assert.match(img,/alt=/);assert.match(img,/width=/);assert.match(img,/height=/);}
for(const [,json] of html.matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/gs))JSON.parse(json);
}
const sitemap=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8');const urls=[...sitemap.matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>m[1]);assert.equal(urls.length,22);assert.equal(new Set(urls).size,22);for(const url of urls)assert(fs.existsSync(path.join(root,new URL(url).pathname,'index.html')));assert.match(fs.readFileSync(path.join(root,'robots.txt'),'utf8'),/Allow: \/[\s\S]*Sitemap: https:\/\/kabuforge.com\/sitemap.xml/);
const inlineBytes=files.filter(f=>f.endsWith('.html')).reduce((n,f)=>n+[...fs.readFileSync(f,'utf8').matchAll(/<script(?![^>]*application\/ld\+json)[^>]*>(.*?)<\/script>/gs)].reduce((v,m)=>v+zlib.gzipSync(m[1]).length,0),0);const js=inlineBytes+files.filter(f=>f.endsWith('.js')).reduce((n,f)=>n+zlib.gzipSync(fs.readFileSync(f)).length,0);assert(js<100*1024);console.log(JSON.stringify({passed:true,htmlPages:titles.size,indexablePages:22,internalReferences:links,gzipJavaScriptBytes:js,checks:['unique metadata','canonical','reciprocal hreflang','internal links/assets','image dimensions and alt','JSON-LD parse','sitemap','robots','JS budget']}));

